name: meow
description: "A cat breeding and social networking app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^16.2.0
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  provider: ^6.1.1
  uuid: ^4.2.2
  intl: ^0.19.0
  path: ^1.8.3
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  flutter_staggered_grid_view: ^0.7.0
  timeago: ^3.6.0
  photo_view: ^0.14.0
  video_player: ^2.8.1
  chewie: ^1.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
